# Generated by Django 4.1.1 on 2022-09-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_posttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
