# Generated by Django 4.1.1 on 2022-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_posttag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='post_tag', to='posts.tag'),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
