# Generated by Django 4.1.1 on 2022-09-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_tag_delete_posttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='post_tags', to='posts.tag'),
        ),
    ]
